fields:
- description: 'TEST: Updated description for client_id'
  mode: NULLABLE
  name: client_id
  type: STRING
- description: 'TEST: Updated description for ad_click_history'
  fields:
  - description: The date associated with the ad_click value
    mode: NULLABLE
    name: key
    type: DATE
  - description: The total number of ad_clicks for the submission_date
    mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: ad_click_history
  type: RECORD
