fields:
- description: 'NEW DESCRIPTION: Unique identifier for the Firefox client installation'
  mode: NULLABLE
  name: client_id
  type: STRING
- description: 'NEW DESCRIPTION: Historical record of advertisement clicks by date'
  fields:
  - description: The date associated with the ad_click value
    mode: NULLABLE
    name: key
    type: DATE
  - description: The total number of ad_clicks for the submission_date
    mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: ad_click_history
  type: RECORD
