fields:
- name: report_period
  type: STRING
  mode: NULLABLE
  description: Report Period - A string in YYYY-MM format representing the month related
    to the CPI data
- name: consumer_price_index
  type: FLOAT
  mode: NULLABLE
  description: Consumer Price Index
- name: country
  type: STRING
  mode: NULLABLE
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- name: base_year
  type: STRING
  mode: NULLABLE
  description: Base Year
- name: last_updated
  type: DATE
  mode: NULLABLE
  description: Last Updated Date
