fields:
- mode: NULLABLE
  name: client_id
  type: STRING
  description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
- mode: NULLABLE
  name: sample_id
  type: INTEGER
  description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
- mode: NULLABLE
  name: profile_group_id
  type: STRING
  description: A UUID uniquely identifying the profile group, not shared with other
    telemetry data.
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping or event data was received on the
    server side. This is typically used as the partition key for the table.
- mode: NULLABLE
  name: metric_date
  type: DATE
  description: Metric Date
- mode: NULLABLE
  name: country
  type: STRING
  description: ISO 3166-1 alpha-2 country code (two-letter abbreviation) indicating
    the country where the activity took place, typically determined by IP geolocation.
    Unknown or NULL values are normally stored as '??'.
- mode: NULLABLE
  name: locale
  type: STRING
  description: Language and/or country-based locale setting that defines the user's
    interface preferences (e.g., en-US, fr-FR).
- mode: NULLABLE
  name: app_version
  type: STRING
  description: The user-visible version string of the application (e.g., "1.0.3",
    "115.0"). For some tables, this may represent only the major version number.
- mode: NULLABLE
  name: normalized_channel
  type: STRING
  description: The release channel on which the application is distributed (e.g.,
    release, beta, nightly, developer edition). Normalized for consistency across
    products.
- mode: NULLABLE
  name: first_seen_date
  type: DATE
  description: The first date on which a client was observed submitting telemetry
    data. This represents the earliest known activity date for the client.
- mode: NULLABLE
  name: attribution_campaign
  type: STRING
  description: Marketing campaign identifier, typically derived from the utm_campaign
    URL parameter or attribution data. Used to track the marketing campaign associated
    with user acquisition.
- mode: NULLABLE
  name: attribution_content
  type: STRING
  description: Specific content or creative variant identifier, typically derived
    from the utm_content URL parameter. Used to differentiate similar content or links
    within the same campaign.
- mode: NULLABLE
  name: attribution_dlsource
  type: STRING
  description: Attribution Download Source - Indicates where installations of Firefox
    originate from.
- mode: NULLABLE
  name: attribution_source
  type: STRING
  description: Traffic source or referrer, typically derived from the utm_source URL
    parameter. Identifies the specific site, service, or location that referred the
    user (e.g., google, facebook, newsletter).
- mode: NULLABLE
  name: attribution_medium
  type: STRING
  description: Marketing channel or medium, typically derived from the utm_medium
    URL parameter. Describes the general category of traffic source (e.g., cpc, email,
    social, organic).
- mode: NULLABLE
  name: attribution_ua
  type: STRING
  description: Attribution User Agent
- mode: NULLABLE
  name: attribution_experiment
  type: STRING
  description: Attribution Experiment - Name/id of the enrolled funnel experiment.
- mode: NULLABLE
  name: attribution_variation
  type: STRING
  description: Attribution Variation - Name/id of the variation cohort used in the
    enrolled funnel experiment.
- mode: NULLABLE
  name: normalized_os
  type: STRING
  description: The normalized name of the operating system running on the client device
    (e.g., Windows, macOS, iOS, Android).
- mode: NULLABLE
  name: normalized_os_version
  type: STRING
  description: Normalized Operating System Version
- mode: NULLABLE
  name: windows_version
  type: STRING
  description: Windows Version
- mode: NULLABLE
  name: distribution_id
  type: STRING
  description: Identifier for the Firefox distribution channel or partner associated
    with this installation. Used to track installations from specific distribution
    agreements.
- mode: NULLABLE
  name: isp
  type: STRING
  description: The name of the internet service provider associated with the client's
    IP address.
- mode: NULLABLE
  name: is_desktop
  type: BOOLEAN
  description: Indicates if the client is included in the desktop KPI
- mode: NULLABLE
  name: days_seen_bits
  type: INTEGER
  description: Days Seen Bits
- mode: NULLABLE
  name: days_desktop_active_bits
  type: INTEGER
  description: Days Desktop Active Bits
- mode: NULLABLE
  name: ping_sent_metric_date
  type: BOOLEAN
  description: Ping Sent on Metric Date
- mode: NULLABLE
  name: ping_sent_week_4
  type: BOOLEAN
  description: Ping Sent Week 4
- mode: NULLABLE
  name: active_metric_date
  type: BOOLEAN
  description: Active on Metric Date
- mode: NULLABLE
  name: retained_week_4
  type: BOOLEAN
  description: Retained Week 4
- mode: NULLABLE
  name: new_profile_metric_date
  type: BOOLEAN
  description: New Profile on Metric Date
- mode: NULLABLE
  name: repeat_profile
  type: BOOLEAN
  description: Repeat Profile
- mode: NULLABLE
  name: retained_week_4_new_profile
  type: BOOLEAN
  description: Retained Week 4 New Profile
- mode: NULLABLE
  name: legacy_telemetry_client_id
  type: STRING
  description: Legacy Telemetry Client Identifier
