fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping is received on the server side.
- mode: NULLABLE
  name: country
  type: STRING
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- mode: NULLABLE
  name: os
  type: STRING
  description: The normalized name of the operating system running at the client.
- mode: NULLABLE
  name: channel
  type: STRING
  description: The normalized channel the application is being distributed on.
- mode: NULLABLE
  name: locale
  type: STRING
  description: User's language and region preference in BCP 47 format combining language
    code and optional country code (e.g., 'en-US', 'de', 'ru'), representing country-based
    and language-based preferences for the user interface
- mode: NULLABLE
  name: app_version
  type: INTEGER
  description: User-visible application version string in semantic versioning format
    (e.g., '1.0.3', '99.3.3') for the browser or mobile app
- mode: NULLABLE
  name: default_search_engine
  type: STRING
- mode: NULLABLE
  name: profile_creation_month
  type: DATE
- mode: NULLABLE
  name: sponsored_tiles_enabled
  type: BOOLEAN
- mode: NULLABLE
  name: tiles_enabled
  type: BOOLEAN
- mode: NULLABLE
  name: pocket_enabled
  type: BOOLEAN
- mode: NULLABLE
  name: pocket_spocs_enabled
  type: BOOLEAN
- mode: NULLABLE
  name: client_count
  type: INTEGER
- mode: NULLABLE
  name: clients_with_ad_engagement
  type: INTEGER
- mode: NULLABLE
  name: clients_with_homepage_ad_engagement
  type: INTEGER
- mode: NULLABLE
  name: clients_with_search_ad_engagement
  type: INTEGER
- mode: NULLABLE
  name: total_uri_count_avg
  type: FLOAT
- mode: NULLABLE
  name: total_uri_count_stddev
  type: FLOAT
- mode: NULLABLE
  name: organic_avg
  type: FLOAT
- mode: NULLABLE
  name: organic_stddev
  type: FLOAT
- mode: NULLABLE
  name: tagged_sap_avg
  type: FLOAT
- mode: NULLABLE
  name: tagged_sap_stddev
  type: FLOAT
- mode: NULLABLE
  name: tagged_follow_on_avg
  type: FLOAT
- mode: NULLABLE
  name: tagged_follow_on_stddev
  type: FLOAT
- mode: NULLABLE
  name: sap_avg
  type: FLOAT
- mode: NULLABLE
  name: sap_stddev
  type: FLOAT
- mode: NULLABLE
  name: ad_click_avg
  type: FLOAT
- mode: NULLABLE
  name: ad_click_stddev
  type: FLOAT
- mode: NULLABLE
  name: ad_click_organic_avg
  type: FLOAT
- mode: NULLABLE
  name: ad_click_organic_stddev
  type: FLOAT
- mode: NULLABLE
  name: search_with_ads_avg
  type: FLOAT
- mode: NULLABLE
  name: search_with_ads_stddev
  type: FLOAT
- mode: NULLABLE
  name: search_with_ads_organic_avg
  type: FLOAT
- mode: NULLABLE
  name: search_with_ads_organic_stddev
  type: FLOAT
- mode: NULLABLE
  name: homepage_visits_avg
  type: FLOAT
- mode: NULLABLE
  name: homepage_visits_stddev
  type: FLOAT
- mode: NULLABLE
  name: sponsored_tile_impressions_avg
  type: FLOAT
- mode: NULLABLE
  name: sponsored_tile_impressions_stddev
  type: FLOAT
- mode: NULLABLE
  name: sponsored_tile_clicks_avg
  type: FLOAT
- mode: NULLABLE
  name: sponsored_tile_clicks_stddev
  type: FLOAT
