fields:
- name: submission_date
  type: DATE
  description: The date when the telemetry ping or event data was received on the
    server side. This is typically used as the partition key for the table.
- name: client_id
  type: STRING
  description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
- name: distribution_id
  mode: NULLABLE
  type: STRING
  description: Identifier for the Firefox distribution channel or partner associated
    with this installation. Used to track installations from specific distribution
    agreements.
