fields:
- name: submission_date
  type: DATE
  description: The date when the telemetry ping is received on the server side.
- name: client_id
  type: STRING
  description: A unique identifier (UUID) for the client.
- name: distribution_id
  mode: NULLABLE
  type: STRING
  description: Identifier for the Firefox distribution source or partner, associated with the install and indicating where the installation originated from
