fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: source
  type: STRING
- mode: NULLABLE
  name: event_type
  type: STRING
- mode: NULLABLE
  name: form_factor
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- mode: NULLABLE
  name: subdivision1
  type: STRING
- mode: NULLABLE
  name: advertiser
  type: STRING
- mode: NULLABLE
  name: release_channel
  type: STRING
- mode: NULLABLE
  name: position
  type: INTEGER
- mode: NULLABLE
  name: provider
  type: STRING
- mode: NULLABLE
  name: match_type
  type: STRING
- mode: NULLABLE
  name: normalized_os
  type: STRING
- mode: NULLABLE
  name: suggest_data_sharing_enabled
  type: BOOLEAN
- mode: NULLABLE
  name: event_count
  type: INTEGER
- mode: NULLABLE
  name: user_count
  type: INTEGER
- mode: NULLABLE
  name: query_type
  type: STRING
