fields:
- description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
  mode: NULLABLE
  name: client_id
  type: STRING
- description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: The first date on which a client was observed submitting telemetry
    data. This represents the earliest known activity date for the client.
  mode: NULLABLE
  name: first_seen_date
  type: DATE
- description: The date when the telemetry ping or event data was received on the
    server side. This is typically used as the partition key for the table.
  mode: NULLABLE
  name: submission_date
  type: DATE
- description: Date when the browser first ran.
  mode: NULLABLE
  name: first_run_date
  type: DATE
- description: First reported country for the client installation
  mode: NULLABLE
  name: first_reported_country
  type: STRING
- description: Name of the first reported isp (Internet Service Provider).
  mode: NULLABLE
  name: first_reported_isp
  type: STRING
- description: The release channel on which the application is distributed (e.g.,
    release, beta, nightly, developer edition). Normalized for consistency across
    products.
  mode: NULLABLE
  name: channel
  type: STRING
- description: Manufacturer of the device where the client is installed.
  mode: NULLABLE
  name: device_manufacturer
  type: STRING
- description: Model of the device where the client is installed.
  mode: NULLABLE
  name: device_model
  type: STRING
- description: Version of the Operating System where the client is originally installed.
  mode: NULLABLE
  name: os_version
  type: STRING
- description: The user-visible version string of the application (e.g., "1.0.3",
    "115.0"). For some tables, this may represent only the major version number.
  mode: NULLABLE
  name: app_version
  type: STRING
- description: Language and/or country-based locale setting that defines the user's
    interface preferences (e.g., en-US, fr-FR).
  mode: NULLABLE
  name: locale
  type: STRING
- description: Determines if a client is activated based on the activation metric
    and a 7 day lag.
  mode: NULLABLE
  name: activated
  type: BOOLEAN
- description: Structure parameter for the campaign name.
  mode: NULLABLE
  name: adjust_campaign
  type: STRING
- description: Structure parameter for the the ad group of a campaign.
  mode: NULLABLE
  name: adjust_ad_group
  type: STRING
- description: Structure parameter for the creative content of a campaign.
  mode: NULLABLE
  name: adjust_creative
  type: STRING
- description: Structure parameter for the network of a campaign.
  mode: NULLABLE
  name: adjust_network
  type: STRING
- description: The source of a client installation.
  mode: NULLABLE
  name: install_source
  type: STRING
- description: Identifier for the Firefox distribution channel or partner associated
    with this installation. Used to track installations from specific distribution
    agreements.
  name: distribution_id
  type: STRING
- description: The utm_campaign this install is attributed to. Reported by the install
    referrer service, not Adjust.
  mode: NULLABLE
  name: play_store_attribution_campaign
  type: STRING
- description: The utm_content this install is attributed to. Reported by the install
    referrer service, not Adjust.
  mode: NULLABLE
  name: play_store_attribution_content
  type: STRING
- description: The utm_medium this install is attributed to. Reported by the install
    referrer service, not Adjust.
  mode: NULLABLE
  name: play_store_attribution_medium
  type: STRING
- description: The utm_source this install is attributed to. Reported by the install
    referrer service, not Adjust.
  mode: NULLABLE
  name: play_store_attribution_source
  type: STRING
- description: The utm_term this install is attributed to. Reported by the install
    referrer service, not Adjust.
  mode: NULLABLE
  name: play_store_attribution_term
  type: STRING
- description: The full install referrer response.
  mode: NULLABLE
  name: play_store_attribution_install_referrer_response
  type: STRING
- description: null
  mode: NULLABLE
  name: meta_attribution_app
  type: STRING
- description: Last reported client locale.
  mode: NULLABLE
  name: last_reported_locale
  type: STRING
- description: Last reported client device manufacturer.
  mode: NULLABLE
  name: last_reported_device_manufacturer
  type: STRING
- description: Last reported client device model.
  mode: NULLABLE
  name: last_reported_device_model
  type: STRING
- description: Last reported client country.
  mode: NULLABLE
  name: last_reported_country
  type: STRING
- description: Last date client seen.
  mode: NULLABLE
  name: last_reported_date
  type: DATE
- description: Last reported client channel.
  mode: NULLABLE
  name: last_reported_channel
  type: STRING
- description: Last reported client campaign network.
  mode: NULLABLE
  name: last_reported_adjust_network
  type: STRING
- description: Last reported campaign name.
  mode: NULLABLE
  name: last_reported_adjust_creative
  type: STRING
- description: Last reported campaign ad group.
  mode: NULLABLE
  name: last_reported_adjust_ad_group
  type: STRING
- description: Last reported campaign name.
  mode: NULLABLE
  name: last_reported_adjust_campaign
  type: STRING
- fields:
  - description: True if the client ever reported a first_session ping.
    mode: NULLABLE
    name: reported_first_session_ping
    type: BOOLEAN
  - description: True if the client ever reported a metrics ping.
    mode: NULLABLE
    name: reported_metrics_ping
    type: BOOLEAN
  - description: True if the client ever reported a baseline ping.
    mode: NULLABLE
    name: reported_baseline_ping
    type: BOOLEAN
  - description: Date when the first reported first_sessin ping is received by the
      server.
    mode: NULLABLE
    name: min_first_session_ping_submission_date
    type: DATE
  - description: Date of first app run as reported in the earliest first_session ping.
    mode: NULLABLE
    name: min_first_session_ping_run_date
    type: DATE
  - description: Date when the first reported metrics ping is received by the server.
    mode: NULLABLE
    name: min_metrics_ping_submission_date
    type: DATE
  - description: Name of the ping that reported the first adjust_network value.
    mode: NULLABLE
    name: adjust_network__source_ping
    type: STRING
  - description: Name of the ping that reports the install_source value.
    mode: NULLABLE
    name: install_source__source_ping
    type: STRING
  - description: Datetime of the ping that reported the first adjust_network value.
    mode: NULLABLE
    name: adjust_network__source_ping_datetime
    type: DATETIME
  - description: Datetime of the ping that reported the first install_source value.
    mode: NULLABLE
    name: install_source__source_ping_datetime
    type: DATETIME
  - description: Datetime of the ping that reported the first play_store_attribution_campaign__ping_datetime
      value.
    mode: NULLABLE
    name: play_store_attribution_campaign__ping_datetime
    type: DATETIME
  - description: Datetime of the ping that reported the first play_store_attribution_content__ping_datetime
      value.
    mode: NULLABLE
    name: play_store_attribution_content__ping_datetime
    type: DATETIME
  - description: Datetime of the ping that reported the first play_store_attribution_medium__ping_datetime
      value.
    mode: NULLABLE
    name: play_store_attribution_medium__ping_datetime
    type: DATETIME
  - description: Datetime of the ping that reported the first play_store_attribution_source__ping_datetime
      value.
    mode: NULLABLE
    name: play_store_attribution_source__ping_datetime
    type: DATETIME
  - description: Datetime of the ping that reported the first play_store_attribution_term__ping_datetime
      value.
    mode: NULLABLE
    name: play_store_attribution_term__ping_datetime
    type: DATETIME
  - description: Datetime of the ping that reported the first play_store_attribution_install_referrer_response__ping_datetime
      value.
    mode: NULLABLE
    name: play_store_attribution_install_referrer_response__ping_datetime
    type: DATETIME
  - description: Datetime of the ping that reported the first meta_attribution_app
      value.
    mode: NULLABLE
    name: meta_attribution_app__ping_datetime
    type: DATETIME
  mode: NULLABLE
  name: metadata
  type: RECORD
