fields:
- mode: NULLABLE
  name: product
  type: STRING
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: country
  type: STRING
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- mode: NULLABLE
  name: device
  type: STRING
- mode: NULLABLE
  name: eligible_share_country
  type: FLOAT
- mode: NULLABLE
  name: clients
  type: INTEGER
- mode: NULLABLE
  name: p_amazon
  type: FLOAT
- mode: NULLABLE
  name: p_other
  type: FLOAT
- mode: NULLABLE
  name: amazon_clients
  type: FLOAT
- mode: NULLABLE
  name: other_clients
  type: FLOAT
- mode: NULLABLE
  name: amazon_clicks
  type: INTEGER
- mode: NULLABLE
  name: other_clicks
  type: INTEGER
- mode: NULLABLE
  name: amazon_clicks_per_client
  type: FLOAT
- mode: NULLABLE
  name: other_clicks_per_client
  type: FLOAT
