fields:
- name: client_id
  mode: NULLABLE
  type: STRING
  description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
- name: sample_id
  mode: NULLABLE
  type: INTEGER
  description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
- name: submission_date
  mode: NULLABLE
  type: DATE
  description: The date when the telemetry ping or event data was received on the
    server side. This is typically used as the partition key for the table.
- name: first_seen_date
  mode: NULLABLE
  type: DATE
  description: The first date on which a client was observed submitting telemetry
    data. This represents the earliest known activity date for the client.
- name: days_since_first_seen
  mode: NULLABLE
  type: INTEGER
  description: Number of days since this client was first seen.
- name: days_since_seen
  mode: NULLABLE
  type: INTEGER
  description: Number of days since this client was last seen. For example, if they
    were seen yesterday, days_since_seen would be 1.
- name: consecutive_days_seen
  mode: NULLABLE
  type: INTEGER
  description: Number of consecutive days this client has been seen. For example,
    if they were missing two days ago but present yesterday & today, consecutive_days_seen
    would be 2.
- name: days_seen_bytes
  mode: NULLABLE
  type: BYTES
  description: Days seen over the past year, represented as bytes.
- name: ad_clicks_on_date
  mode: NULLABLE
  type: INTEGER
  description: Number of ad clicks by this client on this submission date.
- name: total_historic_ad_clicks
  mode: NULLABLE
  type: INTEGER
  description: Total historic ad clicks by this client up to this date (inclusive
    of this date).
- name: first_reported_country
  mode: NULLABLE
  type: STRING
  description: First country reported by this client.
- name: first_reported_isp
  mode: NULLABLE
  type: STRING
  description: First ISP reported by this client.
- name: adjust_network
  mode: NULLABLE
  type: STRING
  description: First Adjust Network reported by this client.
- name: install_source
  mode: NULLABLE
  type: STRING
  description: First install source reported by this client.
