fields:
- mode: NULLABLE
  name: country
  type: STRING
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- mode: NULLABLE
  name: submission_date
  type: DATE
- mode: NULLABLE
  name: device
  type: STRING
- mode: NULLABLE
  name: eligible_share_country
  type: FLOAT
- mode: NULLABLE
  name: live_market_dau
  type: INTEGER
- mode: NULLABLE
  name: urlbar_search_dau
  type: INTEGER
- mode: NULLABLE
  name: suggest_exposed_clients
  type: INTEGER
- mode: NULLABLE
  name: urlbar_search
  type: INTEGER
- mode: NULLABLE
  name: total_impressions
  type: INTEGER
- mode: NULLABLE
  name: spons_impressions
  type: INTEGER
- mode: NULLABLE
  name: spons_clicks
  type: INTEGER
