fields:
- mode: NULLABLE
  name: submission_date_pacific
  type: DATE
- mode: NULLABLE
  name: user_id
  type: STRING
- mode: NULLABLE
  name: insert_id
  type: STRING
- mode: NULLABLE
  name: region
  type: STRING
- mode: NULLABLE
  name: country
  type: STRING
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- mode: NULLABLE
  name: language
  type: STRING
- mode: REPEATED
  name: services
  type: STRING
- mode: REPEATED
  name: oauth_client_ids
  type: STRING
- mode: REPEATED
  name: fxa_services_used
  type: STRING
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: os_used_month
  type: RECORD
- mode: NULLABLE
  name: sync_device_count
  type: INTEGER
- mode: NULLABLE
  name: sync_active_devices_day
  type: INTEGER
- mode: NULLABLE
  name: sync_active_devices_week
  type: INTEGER
- mode: NULLABLE
  name: sync_active_devices_month
  type: INTEGER
- mode: NULLABLE
  name: ua_version
  type: STRING
- mode: NULLABLE
  name: ua_browser
  type: STRING
- mode: NULLABLE
  name: app_version
  type: FLOAT
  description: User-visible application version string in semantic versioning format
    (e.g., '1.0.3', '99.3.3') for the browser or mobile app
- mode: NULLABLE
  name: days_seen_bits
  type: INTEGER
- mode: REPEATED
  name: rollup_events
  type: STRING
- mode: NULLABLE
  name: timestamp
  type: DATETIME
