fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the email recipient contact record in Acoustic Campaign system.

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier used for Acoustic Campaign analytics and tracking purposes.

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier of the specific email mailing or send associated with this recipient event.

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier of the marketing campaign associated with this email event in Acoustic Campaign.

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific email content or creative variant sent to the recipient.

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Date and time when the recipient event occurred, in the API user's configured time zone.

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Classification of the recipient interaction (e.g., sent, opened, clicked, bounced, unsubscribed).

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient contact type (e.g., normal, test, seed) to whom the email was sent.

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body received by the contact (e.g., HTML, plain text, multipart).

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label or name assigned to the clicked link or clickstream element in the email.

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the hyperlink that was clicked through or tracked as a clickstream event.

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason code or description explaining why a contact was suppressed from receiving the email.


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Airflow's execution date should \
    overlap with date inside event_timestamp field
