fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact/recipient who received the email campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Identifier linking to the campaign report in Acoustic Campaign system

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email mailing or send event

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier for the marketing campaign that sent the email

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific email content or template used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred (e.g., sent, opened, clicked) in the API user's timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email engagement event (e.g., Sent, Opened, Clicked, Bounced, Unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient (e.g., TO, CC, BCC) indicating how they received the email

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body received by the contact (e.g., HTML, Plain Text, Multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the clicked link or clickstream tracking identifier

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the hyperlink that was clicked in the email (for click events only)

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why the recipient was suppressed from receiving emails (e.g., hard bounce, unsubscribe, spam complaint)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL partition date representing when the data was ingested into BigQuery (Airflow execution date)
