fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact/recipient who received the email campaign. Used to track individual recipient behavior across multiple mailings.

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Unique identifier for the aggregated report associated with this email event. Links individual recipient events to campaign-level reporting.

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email mailing/send instance. Each mailing represents a distinct email deployment to recipients.

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Unique identifier for the marketing campaign. Multiple mailings can be associated with a single campaign for tracking overall campaign performance.

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific email content version or variant sent to the recipient. Useful for A/B testing and content performance analysis.

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred (sent, opened, clicked, etc.), recorded in the API user's configured timezone.

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of recipient interaction event (e.g., Sent, Open, Click, Bounce, Unsubscribe). Used to classify and analyze different stages of email engagement.

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient who received the email (e.g., seed, test, regular subscriber). Helps filter out test data from production analytics.

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body received by the recipient (HTML, Plain Text, or Multipart). Important for analyzing format-specific engagement patterns.

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name or label assigned to the clicked link within the email. Enables tracking of specific call-to-action performance.

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the hyperlink that was clicked by the recipient. Null for non-click events. Used for clickthrough and conversion tracking.

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why a recipient was suppressed from receiving the email (e.g., unsubscribed, bounced, spam complaint). Critical for maintaining list hygiene.


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Partition date representing Airflow's execution date for the ETL job. Aligns with the date component of event_timestamp for efficient data querying.
