fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received the email campaign. Links to recipient records in Acoustic Campaign for tracking individual user engagement.

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Identifier for the report associated with this recipient event. Used to group recipient-level metrics within specific campaign reports.

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the sent email mailing. Tracks which specific email send operation this recipient event belongs to.

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier for the marketing campaign. Groups multiple mailings under a single campaign for performance analysis.

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the email content variant delivered to the recipient. Useful for A/B testing and content performance analysis.

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the recipient event occurred (send, open, click, etc.) in the API user's timezone. Critical for time-based analysis and engagement tracking.

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of recipient engagement event such as Sent, Opened, Clicked, Bounced, or Unsubscribed. Primary dimension for campaign performance metrics.

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient (e.g., Seed, Test, or Regular contact). Used to filter test recipients from production metrics.

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body delivered to the recipient (HTML, Plain Text, or Multipart). Indicates which email rendering the recipient received.

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined name or label for the clicked link or clickstream. Helps identify which call-to-action or content element drove engagement.

- mode: NULLABLE
  name: url
  type: STRING
  description: Full URL of the hyperlink clicked by the recipient. Enables tracking of specific destinations and conversion paths.

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why a recipient was suppressed from receiving the email (e.g., bounced, unsubscribed, opted out). Critical for list hygiene and compliance tracking.


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date partition key representing Airflow's execution date. Aligns with the date component of event_timestamp for efficient querying and data management.
