fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact or recipient associated with 
    the email event. This ID links email interactions (opens, clicks, bounces) 
    to specific contacts in the Acoustic Campaign system and serves as a key for
    joining with recipient profile data.

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal Acoustic Campaign report identifier used for tracking 
    and aggregating email campaign metrics. This ID groups related email events 
    together for reporting purposes within the Acoustic platform.

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email mailing or send 
    associated with the event. This ID represents a single email deployment 
    instance and is used to track all recipient interactions (opens, clicks, 
    unsubscribes) for that particular send.

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier for the marketing campaign to which the email belongs.
    Multiple mailings can be grouped under a single campaign_id, enabling 
    campaign-level performance analysis and ROI tracking across different email 
    sends.

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific content or creative variation used in
    the email. This enables A/B testing and content performance comparison by 
    tracking which content versions drive better engagement metrics.

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Precise date and time when the email event occurred, recorded in 
    the API user's configured time zone. This timestamp captures the exact 
    moment of recipient interaction (open, click, bounce, etc.) and is used for 
    time-based analysis and event sequencing.

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Classification of the recipient's interaction with the email. 
    Common values include 'Sent', 'Open', 'Click', 'Bounce', 'Unsubscribe', and 
    'OptOut'. This field is used for clustering to optimize query performance 
    and is essential for calculating email engagement metrics.

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the contact based on their relationship to the 
    email send. Distinguishes between different recipient categories such as 
    primary recipients, test sends, seed lists, or suppressed contacts. Used for
    clustering to optimize queries filtering by recipient segment.

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body that was delivered to the contact. 
    Typical values include 'HTML', 'Text', or 'Multipart'. This field tracks 
    which email format the recipient received and is used for clustering to 
    enable efficient analysis of engagement by email format.

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label or name assigned to a tracked link or 
    clickstream within the email. This descriptive name helps identify which 
    call-to-action, button, or hyperlink the recipient clicked, enabling content
    optimization and link performance analysis.

- mode: NULLABLE
  name: url
  type: STRING
  description: Full hyperlink URL that was clicked by the recipient (for Click 
    events) or the destination of a tracked clickstream. This field is populated
    only for click-related events and enables analysis of which links and 
    content drive the most traffic.

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Explanation for why a contact was excluded from receiving the 
    email or why their interaction was suppressed. Common reasons include 
    'Previously Unsubscribed', 'Bounced Email', 'Duplicate Address', or 'Invalid
    Email'. This field helps maintain list hygiene and understand deliverability
    issues.


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL processing date representing Airflow's execution date for the
    data pipeline run. This date should align with the dates in the 
    event_timestamp field and is used for time-based partitioning to optimize 
    query performance and data retention. Data is retained for 775 days based on
    the partition expiration policy.
