fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received the email campaign from Acoustic Campaign system

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal report identifier associated with the email campaign metrics and analytics

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email send/mailing event within Acoustic Campaign

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Campaign identifier linking the email event to a specific marketing campaign in Acoustic

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the email content template or creative used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred (open, click, bounce, etc.) in API user's timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Type of email interaction event (e.g., sent, opened, clicked, bounced, unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Classification of the recipient contact type who received the email (e.g., seed, normal, test)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email body content received by the contact (e.g., HTML, plain text, multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the clicked link or clickstream tracking element in the email

- mode: NULLABLE
  name: url
  type: STRING
  description: Full hyperlink URL that was clicked by the recipient in clickthrough or clickstream events

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason why a contact was excluded from receiving the email (e.g., bounced, unsubscribed, invalid)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date partition for ETL processing aligned with Airflow execution date and event_timestamp
