fields:

# source:
# https://developer.goacoustic.com/acoustic-campaign/reference/rawrecipientdataexport

- mode: NULLABLE
  name: recipient_id
  type: INTEGER
  description: Unique identifier for the contact who received or interacted with the email campaign

- mode: NULLABLE
  name: report_id
  type: INTEGER
  description: Internal Acoustic Campaign report identifier for tracking and analytics purposes

- mode: NULLABLE
  name: mailing_id
  type: INTEGER
  description: Unique identifier for the specific email send/mailing that generated this event

- mode: NULLABLE
  name: campaign_id
  type: INTEGER
  description: Identifier for the parent marketing campaign containing this email send

- mode: NULLABLE
  name: content_id
  type: STRING
  description: Identifier for the specific email content or creative version used in the mailing

- mode: NULLABLE
  name: event_timestamp
  type: DATETIME
  description: Timestamp when the email event occurred in the API user's configured timezone

- mode: NULLABLE
  name: event_type
  type: STRING
  description: Classification of the recipient interaction (e.g., Sent, Opened, Clicked, Bounced, Unsubscribed)

- mode: NULLABLE
  name: recipient_type
  type: STRING
  description: Categorization of the email recipient (e.g., individual contact, seed address, test recipient)

- mode: NULLABLE
  name: body_type
  type: STRING
  description: Format of the email content delivered to the recipient (e.g., HTML, plain text, multipart)

- mode: NULLABLE
  name: click_name
  type: STRING
  description: User-defined label for the clicked link or clickstream tracking identifier

- mode: NULLABLE
  name: url
  type: STRING
  description: Full destination URL for clickthrough or clickstream events

- mode: NULLABLE
  name: suppression_reason
  type: STRING
  description: Reason the recipient was excluded from the mailing (e.g., opted out, bounced, unsubscribed)


###### ETL fields

- mode: NULLABLE
  name: submission_date
  type: DATE
  description: ETL processing date partitioning field aligned with Airflow execution schedule
