fields:
- name: uid
  type: STRING
  mode: NULLABLE
  description: Account ID in hexadecimal format.
- name: normalizedEmail
  type: STRING
  mode: NULLABLE
- name: email
  type: STRING
  mode: NULLABLE
- name: emailVerified
  type: BOOLEAN
  mode: NULLABLE
- name: verifierVersion
  type: INTEGER
  mode: NULLABLE
- name: verifierSetAt
  type: TIMESTAMP
  mode: NULLABLE
- name: createdAt
  type: TIMESTAMP
  mode: NULLABLE
- name: locale
  type: STRING
  mode: NULLABLE
  description: User's language and region preference in BCP 47 format combining language
    code and optional country code (e.g., 'en-US', 'de', 'ru'), representing country-based
    and language-based preferences for the user interface
- name: lockedAt
  type: TIMESTAMP
  mode: NULLABLE
- name: profileChangedAt
  type: TIMESTAMP
  mode: NULLABLE
- name: keysChangedAt
  type: TIMESTAMP
  mode: NULLABLE
- name: ecosystemAnonId
  type: STRING
  mode: NULLABLE
- name: disabledAt
  type: TIMESTAMP
  mode: NULLABLE
- name: metricsOptOutAt
  type: TIMESTAMP
  mode: NULLABLE
- name: atLeast18AtReg
  type: BOOLEAN
  mode: NULLABLE
