fields:
- mode: NULLABLE
  name: client_id
  type: STRING
  description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
- mode: NULLABLE
  name: sample_id
  type: INTEGER
  description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
- mode: NULLABLE
  name: normalized_channel
  type: STRING
  description: The release channel on which the application is distributed (e.g.,
    release, beta, nightly, developer edition). Normalized for consistency across
    products.
- mode: NULLABLE
  name: app_build
  type: STRING
- mode: NULLABLE
  name: app_channel
  type: STRING
- mode: NULLABLE
  name: app_display_version
  type: STRING
  description: User visible version string (e.g. "1.0.3") for the browser.
- mode: NULLABLE
  name: device_manufacturer
  type: STRING
  description: The manufacturer of the device the application is running on.
- mode: NULLABLE
  name: device_model
  type: STRING
  description: The model of the device the application is running on. On Android,
    this is Build.MODEL, the user-visible marketing name, like "Pixel 2 XL".
- mode: NULLABLE
  name: isp
  type: STRING
  description: The name of the internet service provider associated with the client's
    IP address.
- mode: NULLABLE
  name: locale
  type: STRING
  description: Language and/or country-based locale setting that defines the user's
    interface preferences (e.g., en-US, fr-FR).
- mode: NULLABLE
  name: city
  type: STRING
  description: Name of the city in which the activity took place, as determined by
    the IP geolocation.
- mode: NULLABLE
  name: country
  type: STRING
  description: ISO 3166-1 alpha-2 country code (two-letter abbreviation) indicating
    the country where the activity took place, typically determined by IP geolocation.
    Unknown or NULL values are normally stored as '??'.
- mode: NULLABLE
  name: adjust_network
  type: STRING
- mode: NULLABLE
  name: adjust_adgroup
  type: STRING
- mode: NULLABLE
  name: adjust_campaign
  type: STRING
- mode: NULLABLE
  name: adjust_creative
  type: STRING
- mode: NULLABLE
  name: first_seen_date
  type: DATE
  description: The first date on which a client was observed submitting telemetry
    data. This represents the earliest known activity date for the client.
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping or event data was received on the
    server side. This is typically used as the partition key for the table.
- mode: NULLABLE
  name: new_profile
  type: INTEGER
- mode: NULLABLE
  name: activated
  type: INTEGER
