fields:
- mode: NULLABLE
  name: client_id
  type: STRING
  description: A unique identifier (UUID) for the client installation
- mode: NULLABLE
  name: sample_id
  type: INTEGER
  description: Sample identifier (0-99) used to partition clients for analysis, generated
    by the data pipeline based on client_id and consistent across pings
- mode: NULLABLE
  name: normalized_channel
  type: STRING
  description: The normalized channel the application is being distributed on.
- mode: NULLABLE
  name: app_build
  type: STRING
- mode: NULLABLE
  name: app_channel
  type: STRING
- mode: NULLABLE
  name: app_display_version
  type: STRING
  description: User visible version string (e.g. "1.0.3") for the browser.
- mode: NULLABLE
  name: device_manufacturer
  type: STRING
  description: The manufacturer of the device the application is running on.
- mode: NULLABLE
  name: device_model
  type: STRING
  description: The model of the device the application is running on. On Android,
    this is Build.MODEL, the user-visible marketing name, like "Pixel 2 XL".
- mode: NULLABLE
  name: isp
  type: STRING
  description: The name of the internet service provider associated with the client's
    IP address.
- mode: NULLABLE
  name: locale
  type: STRING
  description: User's language and region preference in BCP 47 format combining language
    code and optional country code (e.g., 'en-US', 'de', 'ru'), representing country-based
    and language-based preferences for the user interface
- mode: NULLABLE
  name: city
  type: STRING
  description: Name of the city in which the activity took place, as determined by
    the IP geolocation.
- mode: NULLABLE
  name: country
  type: STRING
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- mode: NULLABLE
  name: adjust_network
  type: STRING
- mode: NULLABLE
  name: adjust_adgroup
  type: STRING
- mode: NULLABLE
  name: adjust_campaign
  type: STRING
- mode: NULLABLE
  name: adjust_creative
  type: STRING
- mode: NULLABLE
  name: first_seen_date
  type: DATE
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping is received on the server side.
- mode: NULLABLE
  name: new_profile
  type: INTEGER
- mode: NULLABLE
  name: activated
  type: INTEGER
