fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: Date when ping is received on the server side.
- name: app_name
  type: STRING
  mode: NULLABLE
  description: Browser name.
- name: app_version
  type: STRING
  mode: NULLABLE
  description: User-visible application version string in semantic versioning format
    (e.g., '1.0.3', '99.3.3') for the browser or mobile app
- name: channel
  type: STRING
  mode: NULLABLE
  description: Browser installation channel installed on the client.
- name: country
  type: STRING
  mode: NULLABLE
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- name: city
  type: STRING
  mode: NULLABLE
  description: City reported by the client.
- name: locale
  type: STRING
  mode: NULLABLE
  description: User's language and region preference in BCP 47 format combining language
    code and optional country code (e.g., 'en-US', 'de', 'ru'), representing country-based
    and language-based preferences for the user interface
- name: os
  type: STRING
  mode: NULLABLE
  description: Operating System reported by the client.
- name: os_version
  type: STRING
  mode: NULLABLE
  description: OS version with windows_build_number as reported by the client.
- name: is_default_browser
  type: BOOLEAN
  mode: NULLABLE
  description: Whether the browser is set as the default browser on the client side.
- name: daily_users
  type: INTEGER
  mode: NULLABLE
  description: Count of users who report a ping in a day.
- name: weekly_users
  type: INTEGER
  mode: NULLABLE
  description: Count of users who have reported a ping over the last 7 days.
- name: monthly_users
  type: INTEGER
  mode: NULLABLE
  description: Count of users who have reported a ping over the last 28 days.
- name: dau
  type: INTEGER
  mode: NULLABLE
  description: Count of users who reported a ping on the submission_date that qualify
    as active.
- name: wau
  type: INTEGER
  mode: NULLABLE
  description: Count of users who have reported a ping over the last 7 days and qualify
    as active.
- name: mau
  type: INTEGER
  mode: NULLABLE
  description: Count of users who have reported a ping over the last 28 days and qualify
    as active.
