fields:
- description: Date corresponding to the unique client count
  mode: NULLABLE
  name: submission_date
  type: DATE
- description: A string representing the app the client activity occurred on
  mode: NULLABLE
  name: meta_attribution_app
  type: STRING
- description: Attributable channel
  mode: NULLABLE
  name: normalized_channel
  type: STRING
- description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
  mode: NULLABLE
  name: country
  type: STRING
- name: ping_count
  type: INTEGER
  mode: NULLABLE
