fields:
- name: first_seen_date
  type: DATE
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
  description: A unique identifier (UUID) for the client installation
- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: Sample identifier (0-99) used to partition clients for analysis, generated
    by the data pipeline based on client_id and consistent across pings
- name: first_reported_country
  type: STRING
  mode: NULLABLE
- name: first_reported_isp
  type: STRING
  mode: NULLABLE
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
- name: adjust_creative
  type: STRING
  mode: NULLABLE
- name: adjust_network
  type: STRING
  mode: NULLABLE
- name: retained_week_2
  type: BOOLEAN
  mode: NULLABLE
- name: retained_week_4
  type: BOOLEAN
  mode: NULLABLE
- name: days_seen_in_first_28_days
  type: INTEGER
  mode: NULLABLE
- name: repeat_first_month_user
  type: BOOLEAN
  mode: NULLABLE
