fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: 'Date field corresponding to the ETL

    processing date. Also, used for

    table partitioning.

    '
- mode: NULLABLE
  name: user_id
  type: STRING
  description: '36-char long hash randomly assigned when the account

    is created.

    '
- mode: NULLABLE
  name: service
  type: STRING
  description: 'The service identifier. For Sync it may be empty or sync.

    For OAuth reliers it is their hex client id.

    Example: sync

    '
- mode: NULLABLE
  name: country
  type: STRING
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- mode: NULLABLE
  name: language
  type: STRING
  description: 'Language settings used by the device.

    '
- mode: NULLABLE
  name: app_version
  type: STRING
  description: User-visible application version string in semantic versioning format
    (e.g., '1.0.3', '99.3.3') for the browser or mobile app
- mode: NULLABLE
  name: os_name
  type: STRING
  description: 'Name of the operating system the device was using.

    E.g. Android

    '
- mode: NULLABLE
  name: os_version
  type: STRING
  description: 'Version of the OS the device was using.

    '
- mode: NULLABLE
  name: days_seen_bits
  type: INTEGER
  description: 'No. of days since the user had activity event.

    '
- mode: NULLABLE
  name: days_seen_in_tier1_country_bits
  type: INTEGER
  description: 'No. of days since seen_in_tier1_country was last True.

    '
- mode: NULLABLE
  name: days_registered_bits
  type: INTEGER
  description: 'No. of days since registration event.

    '
