fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Data submission date
- mode: NULLABLE
  name: country
  type: STRING
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- mode: NULLABLE
  name: newtab_clients
  type: INTEGER
  description: Count of clients available in newtab for submission_date
- mode: NULLABLE
  name: as_clients
  type: INTEGER
  description: Count of clients available in activity-stream for submission_date
- mode: NULLABLE
  name: newtab_visits
  type: INTEGER
  description: Count of visits available in newtab for submission_date
- mode: NULLABLE
  name: as_sessions
  type: INTEGER
  description: Count of sessions available in activity-stream for submission_date
- mode: NULLABLE
  name: conversion_factor
  type: FLOAT
  description: Daily conversion factor allowing the translation of newtab visits to
    activity-stream sessions (as_sessions / newtab_visits)
