fields:
- description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
  mode: NULLABLE
  name: client_id
  type: STRING
- description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: The date associated with the Markov state; as_of_date will not update
    after a year of inactivity as the markov states stop updating
  mode: NULLABLE
  name: as_of_date
  type: DATE
- description: The first date on which a client was observed submitting telemetry
    data. This represents the earliest known activity date for the client.
  mode: NULLABLE
  name: first_seen_date
  type: DATE
- description: Days Since First Seen
  mode: NULLABLE
  name: days_since_first_seen
  type: INTEGER
- description: Days Since Active
  mode: NULLABLE
  name: days_since_active
  type: INTEGER
- description: First Reported Country
  mode: NULLABLE
  name: first_reported_country
  type: STRING
- description: Attribution
  mode: NULLABLE
  name: attribution
  type: RECORD
  fields:
  - mode: NULLABLE
    name: source
    type: STRING
    description: Traffic source or referrer, typically derived from the utm_source
      URL parameter. Identifies the specific site, service, or location that referred
      the user (e.g., google, facebook, newsletter).
  - mode: NULLABLE
    name: medium
    type: STRING
    description: Marketing channel or medium, typically derived from the utm_medium
      URL parameter. Describes the general category of traffic source (e.g., cpc,
      email, social, organic).
  - mode: NULLABLE
    name: campaign
    type: STRING
    description: Marketing campaign identifier, typically derived from the utm_campaign
      URL parameter or attribution data. Used to track the marketing campaign associated
      with user acquisition.
  - mode: NULLABLE
    name: content
    type: STRING
    description: Specific content or creative variant identifier, typically derived
      from the utm_content URL parameter. Used to differentiate similar content or
      links within the same campaign.
  - mode: NULLABLE
    name: experiment
    type: STRING
  - mode: NULLABLE
    name: variation
    type: STRING
  - mode: NULLABLE
    name: dltoken
    type: STRING
  - name: dlsource
    type: STRING
    mode: NULLABLE
  - name: ua
    type: STRING
    mode: NULLABLE
- description: Days Seen Bytes
  mode: NULLABLE
  name: days_seen_bytes
  type: BYTES
- description: Active
  mode: NULLABLE
  name: active
  type: INTEGER
- description: Number of clicks on advertisements. May represent total clicks, clicks
    within a specific time period, or sponsored content clicks depending on context.
  mode: NULLABLE
  name: ad_clicks
  type: INTEGER
- description: Total Historical Ad Clicks
  mode: NULLABLE
  name: total_historic_ad_clicks
  type: INTEGER
