fields:
- mode: NULLABLE
  name: first_seen_date
  type: DATE
  description: Date we first received a baseline ping from the profile.
- mode: NULLABLE
  name: normalized_channel
  type: STRING
  description: Release channel of the app the profile is using.
- name: app_name
  type: STRING
  mode: NULLABLE
  description: App name the profile is using.
- name: app_version
  type: STRING
  mode: NULLABLE
  description: User-visible application version string in semantic versioning format
    (e.g., '1.0.3', '99.3.3') for the browser or mobile app
- name: country
  type: STRING
  mode: NULLABLE
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- name: city
  type: STRING
  mode: NULLABLE
  description: Client's city on the first seen date.
- name: geo_subdivision
  type: STRING
  mode: NULLABLE
  description: Client's geo subdivision on the first seen date.
- name: os
  type: STRING
  mode: NULLABLE
  description: Client's os on the first seen date.
- name: os_version
  type: STRING
  mode: NULLABLE
  description: Client's os version on the first seen date.
- name: device_manufacturer
  type: STRING
  mode: NULLABLE
  description: Client's device manufacturer on the first seen date.
- name: is_mobile
  type: BOOLEAN
  mode: NULLABLE
  description: Indicates if this specific entry is used towards calculating mobile
    DAU.
- name: play_store_attribution_campaign
  type: STRING
  mode: NULLABLE
  description: Play store campaign the profile is attributed to.
- name: play_store_attribution_medium
  type: STRING
  mode: NULLABLE
  description: Play store Medium the profile is attributed to.
- name: play_store_attribution_source
  type: STRING
  mode: NULLABLE
  description: Play store source the profile is attributed to.
- name: play_store_attribution_content
  type: STRING
  mode: NULLABLE
  description: null
- name: play_store_attribution_term
  type: STRING
  mode: NULLABLE
  description: null
- name: meta_attribution_app
  type: STRING
  mode: NULLABLE
  description: Facebook app linked to paid marketing.
- name: install_source
  type: STRING
  mode: NULLABLE
  description: The source of a profile installation.
- name: adjust_ad_group
  type: STRING
  mode: NULLABLE
  description: Adjust Ad Group the profile is attributed to.
- name: adjust_campaign
  type: STRING
  mode: NULLABLE
  description: Adjust Campaign the profile is attributed to.
- name: adjust_creative
  type: STRING
  mode: NULLABLE
  description: Adjust Creative the profile is attributed to.
- name: adjust_network
  type: STRING
  mode: NULLABLE
  description: Adjust Network the profile is attributed to.
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: Identifier for the Firefox distribution source or partner, associated
    with the install and indicating where the installation originated from
- name: device_type
  type: STRING
  mode: NULLABLE
  description: 'On Apple devices allows us to differentiate between iPhone and iPad.
    On Android devices the value is always "Android".

    '
- name: new_profiles
  type: INTEGER
  mode: NULLABLE
  description: 'Number of new profiles.

    '
- name: activations
  type: INTEGER
  mode: NULLABLE
  description: 'Count of new profiles that activated.

    '
- name: retained_week_4
  type: INTEGER
  mode: NULLABLE
  description: 'The number of new profiles retained after week 4.

    '
