fields:
- description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
  mode: NULLABLE
  name: client_id
  type: STRING
- description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: The date associated with the Markov state; as_of_date will not update
    after a year of inactivity as the markov states stop updating
  mode: NULLABLE
  name: as_of_date
  type: DATE
- description: The first date on which a client was observed submitting telemetry
    data. This represents the earliest known activity date for the client.
  mode: NULLABLE
  name: first_seen_date
  type: DATE
- description: Days Since First Seen
  mode: NULLABLE
  name: days_since_first_seen
  type: INTEGER
- description: Days Since Seen
  mode: NULLABLE
  name: days_since_seen
  type: INTEGER
- description: Days Seen Bytes
  mode: NULLABLE
  name: days_seen_bytes
  type: BYTES
- description: Durations
  mode: NULLABLE
  name: durations
  type: INTEGER
- description: Number of clicks on advertisements. May represent total clicks, clicks
    within a specific time period, or sponsored content clicks depending on context.
  mode: NULLABLE
  name: ad_clicks
  type: INTEGER
- description: Total Historical Ad Clicks
  mode: NULLABLE
  name: total_historic_ad_clicks
  type: INTEGER
- description: Adjust Network
  mode: NULLABLE
  name: adjust_network
  type: STRING
- description: First Reported Country
  mode: NULLABLE
  name: first_reported_country
  type: STRING
- description: First Reported ISP
  mode: NULLABLE
  name: first_reported_isp
  type: STRING
