fields:
- description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
  mode: NULLABLE
  name: client_id
  type: STRING
- description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: History of ad_clicks for a user, by submission_date
  fields:
  - description: The date associated with the ad_click value
    mode: NULLABLE
    name: key
    type: DATE
  - description: The total number of ad_clicks for the submission_date
    mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: ad_click_history
  type: RECORD
