fields:
- description: A unique identifier (UUID) for the client installation
  mode: NULLABLE
  name: client_id
  type: STRING
- description: Sample identifier (0-99) used to partition clients for analysis, generated
    by the data pipeline based on client_id and consistent across pings
  mode: NULLABLE
  name: sample_id
  type: INTEGER
- description: History of ad_clicks for a user, by submission_date
  fields:
  - description: The date associated with the ad_click value
    mode: NULLABLE
    name: key
    type: DATE
  - description: The total number of ad_clicks for the submission_date
    mode: NULLABLE
    name: value
    type: INTEGER
  mode: REPEATED
  name: ad_click_history
  type: RECORD
