fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping or event data was received on the
    server side. This is typically used as the partition key for the table.
- mode: NULLABLE
  name: client_id
  type: STRING
  description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
- mode: NULLABLE
  name: sample_id
  type: INTEGER
  description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
- mode: NULLABLE
  name: normalized_channel
  type: STRING
  description: The release channel on which the application is distributed (e.g.,
    release, beta, nightly, developer edition). Normalized for consistency across
    products.
- mode: NULLABLE
  name: distribution_id
  type: STRING
  description: Identifier for the Firefox distribution channel or partner associated
    with this installation. Used to track installations from specific distribution
    agreements.
- mode: NULLABLE
  name: is_dau
  type: BOOLEAN
  description: Count of Daily Active Users (DAU) or a flag indicating whether the
    client qualifies as a daily active user. DAU typically represents unique users
    active within a 24-hour period.
- mode: NULLABLE
  name: policies_count
  type: INTEGER
  description: 'A uint with the number of active enterprise policies, collected once
    at startup.

    This metric was generated to correspond to the Legacy Telemetry scalar policies.count.

    '
- mode: NULLABLE
  name: policies_is_enterprise
  type: BOOLEAN
  description: 'Attempt to determine if the user is an enterprise user based on various
    signals.

    This metric was generated to correspond to the Legacy Telemetry scalar policies.is_enterprise

    '
