fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date when telemetry ping was received on the server side, used as
    the primary time dimension for daily partitioning
- name: first_seen_year
  type: INTEGER
  mode: NULLABLE
  description: Year of the user's first ping submission, enabling cohort 
    analysis and user retention tracking
- name: channel
  type: STRING
  mode: NULLABLE
  description: Firefox distribution channel (e.g., release, beta, nightly, esr) 
    indicating the build type
- name: app_name
  type: STRING
  mode: NULLABLE
  description: 'Application identifier for Firefox Desktop, with distribution_id appended
    for MozillaOnline and BrowserStack (ISP) distributions'
- name: country
  type: STRING
  mode: NULLABLE
  description: Two-letter ISO country code derived from IP geolocation, with 
    '??' for unknown or NULL values
- name: city
  type: STRING
  mode: NULLABLE
  description: City name reported by the client telemetry ping for geographic 
    analysis
- name: locale
  type: STRING
  mode: NULLABLE
  description: User interface language and regional preferences (e.g., en-US, 
    fr-FR) configured by the user
- name: os
  type: STRING
  mode: NULLABLE
  description: Normalized operating system name (e.g., Windows, macOS, Linux) 
    running on the client device
- name: os_grouped
  type: STRING
  mode: NULLABLE
  description: High-level OS category grouping similar operating systems for 
    aggregate analysis
- name: os_version
  type: STRING
  mode: NULLABLE
  description: Full operating system version string reported by the client
- name: os_version_major
  type: INTEGER
  mode: NULLABLE
  description: Major version number of the OS (e.g., 100 from version 100.9.11) 
    for trend analysis
- name: os_version_minor
  type: INTEGER
  mode: NULLABLE
  description: Minor version number of the OS (e.g., 9 from version 100.9.11) 
    for detailed version tracking
- name: os_version_build
  type: STRING
  mode: NULLABLE
  description: OS build identifier providing additional version granularity 
    beyond major and minor versions
- name: windows_build_number
  type: INTEGER
  mode: NULLABLE
  description: 'Windows-specific build number (e.g., 22000) for Windows platform analysis,
    NULL for non-Windows systems'
- name: app_version
  type: STRING
  mode: NULLABLE
  description: Human-readable Firefox version string (e.g., 1.0.3) displayed to 
    users
- name: app_version_major
  type: NUMERIC
  mode: NULLABLE
  description: 'Major version number of Firefox (e.g., 123 from version 123.0) for
    version adoption tracking'
- name: app_version_minor
  type: NUMERIC
  mode: NULLABLE
  description: 'Minor version number of Firefox (e.g., 0 from version 123.0) for point
    release analysis'
- name: app_version_patch_revision
  type: NUMERIC
  mode: NULLABLE
  description: 'Patch revision identifier for bug fix releases within a version'
- name: app_version_is_major_release
  type: BOOLEAN
  mode: NULLABLE
  description: 'Boolean flag indicating whether this version represents a major Firefox
    release milestone'
- name: is_default_browser
  type: BOOLEAN
  mode: NULLABLE
  description: Boolean indicating if Firefox is set as the default browser on 
    the user's system
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: Distribution partner identifier for tracking Firefox installs 
    from specific partners or channels
- name: activity_segment
  type: STRING
  mode: NULLABLE
  description: User engagement classification (e.g., infrequent, casual, 
    regular, core) based on browsing behavior patterns
- name: attribution_medium
  type: STRING
  mode: NULLABLE
  description: 'Marketing channel medium (e.g., referral, organic) tracking user acquisition
    sources'
- name: attribution_source
  type: STRING
  mode: NULLABLE
  description: 'Specific acquisition source (e.g., search, partner campaign) for marketing
    attribution analysis'
- name: daily_users
  type: INTEGER
  mode: NULLABLE
  description: 'Count of unique users who submitted a ping on the submission_date,
    aggregated by dimension groupings'
- name: weekly_users
  type: INTEGER
  mode: NULLABLE
  description: 'Count of unique users who submitted a ping in the 7 days up to and
    including submission_date'
- name: monthly_users
  type: INTEGER
  mode: NULLABLE
  description: 'Count of unique users who submitted a ping in the 28 days up to and
    including submission_date'
- name: dau
  type: INTEGER
  mode: NULLABLE
  description: 'Daily Active Users count based on activity flags indicating actual
    browser usage on submission_date'
- name: wau
  type: INTEGER
  mode: NULLABLE
  description: 'Weekly Active Users count based on activity flags indicating browser
    usage in the past 7 days'
- name: mau
  type: INTEGER
  mode: NULLABLE
  description: 'Monthly Active Users count based on activity flags indicating browser
    usage in the past 28 days'
