fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: Date when telemetry ping was received server-side; used for daily
    partitioning and temporal analysis
- name: first_seen_year
  type: INTEGER
  mode: NULLABLE
  description: Year when client first appeared in telemetry, extracted from 
    first_seen_date; useful for cohort analysis
- name: channel
  type: STRING
  mode: NULLABLE
  description: Firefox release channel (e.g., release, beta, nightly, esr) 
    indicating distribution stream
- name: app_name
  type: STRING
  mode: NULLABLE
  description: 'Application identifier, typically Firefox Desktop; includes distribution_id
    suffix for MozillaOnline and ISP markers for BrowserStack clients'
- name: country
  type: STRING
  mode: NULLABLE
  description: ISO 3166-1 alpha-2 country code derived from IP geolocation; '??'
    indicates unknown or invalid location
- name: city
  type: STRING
  mode: NULLABLE
  description: City name as reported by the client's telemetry ping
- name: locale
  type: STRING
  mode: NULLABLE
  description: User interface language preference in BCP 47 format (e.g., 
    'en-US', 'de-DE') combining language and optional region
- name: os
  type: STRING
  mode: NULLABLE
  description: Normalized operating system name (e.g., Windows, Darwin, Linux) 
    standardized across telemetry
- name: os_grouped
  type: STRING
  mode: NULLABLE
  description: Grouped operating system category for high-level OS segmentation
- name: os_version
  type: STRING
  mode: NULLABLE
  description: Full operating system version string as reported by the client
- name: os_version_major
  type: INTEGER
  mode: NULLABLE
  description: Major version number of the OS (first segment, e.g., '10' in 
    '10.15.7')
- name: os_version_minor
  type: INTEGER
  mode: NULLABLE
  description: Minor version number of the OS (second segment, e.g., '15' in 
    '10.15.7')
- name: os_version_build
  type: STRING
  mode: NULLABLE
  description: Build identifier for the operating system version
- name: windows_build_number
  type: INTEGER
  mode: NULLABLE
  description: 'Windows-specific build number (e.g., 22000 for Windows 11); NULL for
    non-Windows platforms'
- name: app_version
  type: STRING
  mode: NULLABLE
  description: Complete semantic version string of Firefox (e.g., '120.0.1') 
    visible to users
- name: app_version_major
  type: NUMERIC
  mode: NULLABLE
  description: 'Major version number of Firefox (e.g., ''120'' from ''120.0.1'')'
- name: app_version_minor
  type: NUMERIC
  mode: NULLABLE
  description: 'Minor version number of Firefox (e.g., ''0'' from ''120.0.1'')'
- name: app_version_patch_revision
  type: NUMERIC
  mode: NULLABLE
  description: 'Patch revision number from the version string (e.g., ''1'' from ''120.0.1'')'
- name: app_version_is_major_release
  type: BOOLEAN
  mode: NULLABLE
  description: 'Flag indicating whether this version represents a major Firefox release'
- name: is_default_browser
  type: BOOLEAN
  mode: NULLABLE
  description: Boolean indicating if Firefox is configured as the system's 
    default browser
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: Identifier for custom Firefox distributions and partnerships
- name: activity_segment
  type: STRING
  mode: NULLABLE
  description: User activity classification (e.g., infrequent, casual, regular, 
    core) based on usage patterns
- name: attribution_medium
  type: STRING
  mode: NULLABLE
  description: 'Marketing attribution medium (e.g., referral, organic, cpc) for install
    source tracking'
- name: attribution_source
  type: STRING
  mode: NULLABLE
  description: 'Marketing attribution source (e.g., google, bing, mozilla.org) identifying
    acquisition channel'
- name: daily_users
  type: INTEGER
  mode: NULLABLE
  description: 'Count of unique users who sent pings on submission_date; aggregated
    using COUNTIF(is_daily_user)'
- name: weekly_users
  type: INTEGER
  mode: NULLABLE
  description: 'Count of unique users who sent pings within the 7-day window ending
    on submission_date; aggregated using COUNTIF(is_weekly_user)'
- name: monthly_users
  type: INTEGER
  mode: NULLABLE
  description: 'Count of unique users who sent pings within the 28-day window ending
    on submission_date; aggregated using COUNTIF(is_monthly_user)'
- name: dau
  type: INTEGER
  mode: NULLABLE
  description: 'Daily Active Users count based on meaningful activity (not just pings)
    on submission_date; aggregated using COUNTIF(is_dau)'
- name: wau
  type: INTEGER
  mode: NULLABLE
  description: 'Weekly Active Users count based on meaningful activity within the
    7-day window; aggregated using COUNTIF(is_wau)'
- name: mau
  type: INTEGER
  mode: NULLABLE
  description: 'Monthly Active Users count based on meaningful activity within the
    28-day window; aggregated using COUNTIF(is_mau)'
