fields:
- name: submission_date
  type: DATE
  mode: NULLABLE
  description: The date when the telemetry ping is received on the server side.
- name: days_seen_bytes
  type: BYTES
  mode: NULLABLE
- name: client_id
  type: STRING
  mode: NULLABLE
  description: A unique identifier (UUID) for the client installation
- name: sample_id
  type: INTEGER
  mode: NULLABLE
  description: Sample identifier (0-99) used to partition clients for analysis, generated
    by the data pipeline based on client_id and consistent across pings
- name: first_run_date
  type: DATE
  mode: NULLABLE
- name: durations
  type: INTEGER
  mode: NULLABLE
- name: days_seen_session_start_bits
  type: INTEGER
  mode: NULLABLE
- name: days_seen_session_end_bits
  type: INTEGER
  mode: NULLABLE
- name: normalized_channel
  type: STRING
  mode: NULLABLE
  description: The normalized channel the application is being distributed on.
- name: normalized_os
  type: STRING
  mode: NULLABLE
  description: The normalized name of the operating system running at the client.
- name: normalized_os_version
  type: STRING
  mode: NULLABLE
- name: android_sdk_version
  type: STRING
  mode: NULLABLE
  description: The optional Android specific SDK version of the software running on
    this hardware device.
- name: locale
  type: STRING
  mode: NULLABLE
  description: User's language and region preference in BCP 47 format combining language
    code and optional country code (e.g., 'en-US', 'de', 'ru'), representing country-based
    and language-based preferences for the user interface
- name: city
  type: STRING
  mode: NULLABLE
  description: Name of the city in which the activity took place, as determined by
    the IP geolocation.
- name: country
  type: STRING
  mode: NULLABLE
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- name: app_build
  type: STRING
  mode: NULLABLE
- name: app_channel
  type: STRING
  mode: NULLABLE
- name: app_display_version
  type: STRING
  mode: NULLABLE
  description: User visible version string (e.g. "1.0.3") for the browser.
- name: architecture
  type: STRING
  mode: NULLABLE
- name: device_manufacturer
  type: STRING
  mode: NULLABLE
- name: device_model
  type: STRING
  mode: NULLABLE
- name: telemetry_sdk_build
  type: STRING
  mode: NULLABLE
  description: The version of the Glean SDK at the time the ping was collected (e.g.
    25.0.0).
- name: first_seen_date
  type: DATE
  mode: NULLABLE
- name: is_new_profile
  type: BOOLEAN
  mode: NULLABLE
- name: isp
  type: STRING
  mode: NULLABLE
- name: distribution_id
  type: STRING
  mode: NULLABLE
  description: Identifier for the Firefox distribution source or partner, associated
    with the install and indicating where the installation originated from
- name: geo_subdivision
  type: STRING
  mode: NULLABLE
