fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping or event data was received on the
    server side. This is typically used as the partition key for the table.
- mode: NULLABLE
  name: sample_id
  type: INTEGER
  description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
- mode: NULLABLE
  name: client_id
  type: STRING
  description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
- mode: NULLABLE
  name: activations_count
  type: INTEGER
- mode: NULLABLE
  name: active_day_count
  type: INTEGER
- mode: NULLABLE
  name: searches
  type: INTEGER
- mode: NULLABLE
  name: searches_with_ads
  type: INTEGER
  description: Number of search queries that returned results including advertisements.
    Used as a monetization metric.
- mode: NULLABLE
  name: ad_clicks
  type: INTEGER
  description: Number of clicks on advertisements. May represent total clicks, clicks
    within a specific time period, or sponsored content clicks depending on context.
- fields:
  - mode: NULLABLE
    name: sent_baseline_ping
    type: BOOLEAN
  - mode: NULLABLE
    name: sent_metrics_search_data
    type: BOOLEAN
  - mode: NULLABLE
    name: activated_on_this_day
    type: BOOLEAN
  mode: NULLABLE
  name: metadata
  type: RECORD
