name: Trigger Schema Update Agent

on:
  issues:
    types: [labeled]

jobs:
  trigger-agent:
    if: github.event.label.name == 'approved'
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Chicory Agent
        env:
          CHICORY_TOKEN: ${{ secrets.CHICORY_TOKEN }}
          CHICORY_AGENT_NAME: ${{ secrets.CHICORY_AGENT_NAME }}
          CHICORY_PROJECT_ID: ${{ secrets.CHICORY_PROJECT_ID }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          # Trigger the agent
          RESPONSE=$(curl -X POST https://app.chicory.ai/api/v1/projects/$CHICORY_PROJECT_ID/runs \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $CHICORY_TOKEN" \
            -d "{
              \"agent_name\": \"$CHICORY_AGENT_NAME\",
              \"input\": [
                {
                  \"parts\": [
                    {
                      \"content_type\": \"text/plain\",
                      \"content\": \"Issue Number: $ISSUE_NUMBER, Database Name: moz-fx-data-shared-prod\"
                    }
                  ],
                  \"created_at\": \"$(date -u +%Y-%m-%dT%H:%M:%S.000Z)\"
                }
              ]
            }")
          
          # Extract run_id
          RUN_ID=$(echo $RESPONSE | jq -r '.run_id')
          echo "Agent run started with ID: $RUN_ID"
          
          # Poll for completion (20 minutes = 1200 seconds, check every 30 seconds)
          for i in {1..40}; do
            sleep 30
            STATUS=$(curl -X GET https://app.chicory.ai/api/v1/projects/$CHICORY_PROJECT_ID/runs/$RUN_ID \
              -H "Authorization: Bearer $CHICORY_TOKEN" | jq -r '.status')
            
            echo "Poll attempt $i: Status = $STATUS"
            
            if [ "$STATUS" == "completed" ]; then
              echo "✅ Agent completed successfully!"
              exit 0
            elif [ "$STATUS" == "failed" ]; then
              echo "❌ Agent failed"
              exit 1
            fi
          done
          
          echo "⏱️ Timeout: Agent still running after 20 minutes"