fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: 'Represents ETL job date.

    Also, used for table partitioning.

    '
- mode: NULLABLE
  name: user_id
  type: STRING
  description: 'A 36 char long hash value representing

    User ID (registered user).

    Also, used as a clustering field.

    '
- mode: NULLABLE
  name: country
  type: STRING
  description: Two-letter ISO 3166-1 alpha-2 country code where the user activity
    occurred, determined by IP geolocation (unknown values may be stored as '??')
- mode: NULLABLE
  name: language
  type: STRING
  description: 'User''s language.

    '
- mode: NULLABLE
  name: app_version
  type: STRING
  description: User-visible application version string in semantic versioning format
    (e.g., '1.0.3', '99.3.3') for the browser or mobile app
- mode: NULLABLE
  name: os_name
  type: STRING
  description: 'OS on which the app was running.

    For example: Android.

    '
- mode: NULLABLE
  name: os_version
  type: STRING
  description: 'Version of the OS the device was using.

    '
- mode: NULLABLE
  name: seen_in_tier1_country
  type: BOOLEAN
  description: 'Set to True if a user sent an event from

    one of the following countries for

    a specific submission_date:

    (''United States'',''France'',

    ''Germany'',''United Kingdom'',''Canada'')

    '
- mode: NULLABLE
  name: registered
  type: BOOLEAN
  description: 'Set to True if the user submitted

    the event_type of `fxa_reg - complete`

    event on the specific submission_date.

    '
- mode: NULLABLE
  name: monitor_only
  type: BOOLEAN
  description: 'Set to True if the user contains events of

    event_type `fxa_rp - engage` only

    for service `fx-monitor`.

    '
