fields:
- mode: NULLABLE
  name: submission_date
  type: DATE
  description: The date when the telemetry ping or event data was received on the
    server side. This is typically used as the partition key for the table.
- mode: NULLABLE
  name: client_id
  type: STRING
  description: A unique identifier for the user, client, or customer. Format may vary
    by system (UUID for telemetry clients, hexadecimal for FxA accounts, integer for
    subscription systems).
- mode: NULLABLE
  name: sample_id
  type: INTEGER
  description: A pipeline-generated sample ID ranging from 0-99, derived by hashing
    client_id. Used for sampling and filtering data during analysis. This value should
    remain consistent across pings for the same client.
- mode: NULLABLE
  name: country
  type: STRING
  description: ISO 3166-1 alpha-2 country code (two-letter abbreviation) indicating
    the country where the activity took place, typically determined by IP geolocation.
    Unknown or NULL values are normally stored as '??'.
- mode: NULLABLE
  name: app_version
  type: STRING
  description: The user-visible version string of the application (e.g., "1.0.3",
    "115.0"). For some tables, this may represent only the major version number.
- mode: NULLABLE
  name: distribution_id
  type: STRING
  description: Identifier for the Firefox distribution channel or partner associated
    with this installation. Used to track installations from specific distribution
    agreements.
- mode: NULLABLE
  name: locale
  type: STRING
  description: Language and/or country-based locale setting that defines the user's
    interface preferences (e.g., en-US, fr-FR).
- mode: NULLABLE
  name: search_cohort
  type: STRING
- mode: NULLABLE
  name: addon_version
  type: STRING
- mode: NULLABLE
  name: os
  type: STRING
  description: The normalized name of the operating system running on the client device
    (e.g., Windows, macOS, iOS, Android).
- mode: NULLABLE
  name: channel
  type: STRING
  description: The release channel on which the application is distributed (e.g.,
    release, beta, nightly, developer edition). Normalized for consistency across
    products.
- mode: NULLABLE
  name: profile_creation_date
  type: INTEGER
- mode: NULLABLE
  name: default_search_engine
  type: STRING
- mode: NULLABLE
  name: default_search_engine_data_load_path
  type: STRING
- mode: NULLABLE
  name: default_search_engine_data_submission_url
  type: STRING
- mode: NULLABLE
  name: profile_age_in_days
  type: INTEGER
- mode: NULLABLE
  name: active_addons_count_mean
  type: FLOAT
- mode: NULLABLE
  name: user_pref_browser_search_region
  type: STRING
- mode: NULLABLE
  name: os_version
  type: STRING
- mode: NULLABLE
  name: max_concurrent_tab_count_max
  type: INTEGER
- mode: NULLABLE
  name: tab_open_event_count_sum
  type: INTEGER
- mode: NULLABLE
  name: active_hours_sum
  type: FLOAT
- mode: NULLABLE
  name: subsession_hours_sum
  type: FLOAT
- mode: NULLABLE
  name: sessions_started_on_this_day
  type: INTEGER
- mode: NULLABLE
  name: organic
  type: INTEGER
- mode: NULLABLE
  name: sap
  type: INTEGER
- mode: NULLABLE
  name: unknown
  type: INTEGER
- mode: NULLABLE
  name: tagged_sap
  type: INTEGER
- mode: NULLABLE
  name: tagged_follow_on
  type: INTEGER
- mode: NULLABLE
  name: ad_click
  type: INTEGER
- mode: NULLABLE
  name: search_with_ads
  type: INTEGER
- mode: NULLABLE
  name: total_searches
  type: INTEGER
- mode: NULLABLE
  name: tagged_searches
  type: INTEGER
- fields:
  - mode: NULLABLE
    name: key
    type: STRING
  - fields:
    - mode: REPEATED
      name: total_searches
      type: INTEGER
    - mode: REPEATED
      name: tagged_searches
      type: INTEGER
    - mode: REPEATED
      name: search_with_ads
      type: INTEGER
    - mode: REPEATED
      name: ad_click
      type: INTEGER
    mode: NULLABLE
    name: value
    type: RECORD
  mode: REPEATED
  name: engine_searches
  type: RECORD
- mode: NULLABLE
  name: days_seen_bytes
  type: BYTES
- mode: NULLABLE
  name: days_searched_bytes
  type: BYTES
- mode: NULLABLE
  name: days_tagged_searched_bytes
  type: BYTES
- mode: NULLABLE
  name: days_searched_with_ads_bytes
  type: BYTES
- mode: NULLABLE
  name: days_clicked_ads_bytes
  type: BYTES
- mode: NULLABLE
  name: days_created_profile_bytes
  type: BYTES
- mode: NULLABLE
  name: profile_group_id
  type: STRING
  description: A UUID uniquely identifying the profile group, not shared with other
    telemetry data.
